### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by dev-bello** [Triellis/Enchanted-Oasis#214]
I tried to clone the app, but it won't connect to my DB. Is there anything I'm doing wrong?

**Comment by Codesmith28** [comment]
Hello dev-bello,

Could you provide more details about the issue you're encountering while trying to clone the app and connect to your database? This will help me understand the problem better and provide you with an appropriate solution.

Best regards,
Codesmith28

**Comment by dev-bello** [comment]
> Hello dev-bello,
> 
> 
> 
> Could you provide more details about the issue you're encountering while trying to clone the app and connect to your database? This will help me understand the problem better and provide you with an appropriate solution.
> 
> 
> 
> Best regards,
> 
> Codesmith28

**Comment by dev-bello** [comment]
Actually after I cloned it I created an .env file and pasted my secret key and mongouri, same name of how you linked it to the DB.ts the app ran but the database refuses to link and I can't also sign in cuz it doesn't have a database. Any more details you need just you can ask!

**Comment by JeelRajodiya** [comment]
> Actually after I cloned it I created an .env file and pasted my secret key and mongouri, same name of how you linked it to the D

You are supposed to create your own database on the cloud, if you wish to contribute

**Comment by dev-bello** [comment]
Can I like message you somewhere? To share more details if you don't mind

**Comment by Codesmith28** [comment]
I think you have **not** included the following in the .env file apart from the **MONGO_URI** :

- SECRET
- NEXTAUTH_URL
- SUPABASE_URL
- SUPABASE_ANON_KEY

**Comment by dev-bello** [comment]
I will add them the see, if it works or not I'll get back to you. I'm hoping you don't mind tho?

**Comment by dev-bello** [comment]
![image](https://github.com/enchanted-oasis-org/Enchanted-Oasis/assets/110071980/56eaae39-9835-4953-8375-180f3ba557c4)
 
After adding all, collections still empty 🥹


![image](https://github.com/enchanted-oasis-org/Enchanted-Oasis/assets/110071980/5b35d3b6-b348-40c5-b813-50376e9100cb)

**Comment by dev-bello** [comment]
Hello sir! Seems I'm dried up here 😭
